---
- stat: path=/var/lib/kubelet/kubeconfig
  register: kubeconfig_stat

- name: |
    "3.1.1 Ensure that the kubeconfig file permissions are set to 644 or more restrictive (Manual)"
    "3.1.2 Ensure that the kubelet kubeconfig file ownership is set to root:root (Manual)"
  file:
    path: /var/lib/kubelet/kubeconfig
    owner: root
    group: root
    mode: 0644
    state: file
  when: kubeconfig_stat.stat.exists == True
  tags:
    - section_3
    - section_3.1.1
    - section_3.1.2

- stat: path=/etc/kubernetes/kubelet/kubelet-config.json
  register: kubeletconfig_stat

- name: |
    "3.1.3 Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Manual)"
    "3.1.4"
  file:
    path: /etc/kubernetes/kubelet/kubelet-config.json
    owner: root
    group: root
    mode: 0644
    state: file
  when: kubeletconfig_stat.stat.exists == True
  tags:
    - section3
    - section_3.1.3
    - section_3.1.4



