---
- name: 4.1.1 Ensure that the cluster-admin role is only used where required (Manual)
  debug: msg="TODO"
  tags:
    - section_4.1.1.yml
    - section_4
    - section_4.1

- name: 4.1.2 Minimize access to secrets (Manual)
  debug: msg="TODO"
  tags:
    - section_4.1.2.yml
    - section_4
    - section_4.1

- name: 4.1.3 Minimize wildcard use in Roles and ClusterRoles (Manual)
  debug: msg="TODO"
  tags:
    - section_4.1.3.yml
    - section_4
    - section_4.1

- name: 4.1.4 Minimize access to create pods (Manual)
  debug: msg="TODO"
  tags:
    - section_4.1.4.yml
    - section_4
    - section_4.1

- name: 4.1.5 Ensure that default service accounts are not actively used.(Manual)
  command: kubectl patch serviceaccount default -p $'automountServiceAccountToken:false'
  tags:
    - section_4.1.5.yml
    - section_4
    - section_4.1

- name: 4.1.6 Ensure that Service Account Tokens are only mounted where necessary (Manual)
  debug: msg="TODO"
  tags:
    - section_4.1.6.yml
    - section_4

